#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 07, 2019 10:11:46 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import sign_up_support
global username

def sign_up():
    import sign_in as si
    root.destroy()
    si.vp_start_gui()

def return_back():
    import front_page as fp
    root.destroy()
    fp.vp_start_gui()

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global w, root
    root = tk.Tk()
    root.state('zoomed')
    top = Toplevel1 (root)
    sign_up_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    sign_up_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1250x650")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.ask_username = tk.Message(top)
        self.ask_username.place(relx=0.385, rely=0.28, relheight=0.05
                , relwidth=0.185)
        self.ask_username.configure(background="#ffffff")
        self.ask_username.configure(font="-family {Yu Gothic Light} -size 22")
        self.ask_username.configure(foreground="#7b003e")
        self.ask_username.configure(highlightbackground="#d9d9d9")
        self.ask_username.configure(highlightcolor="black")
        self.ask_username.configure(text='''Enter a username''')
        self.ask_username.configure(width=356)

        self.enter_username = tk.Entry(top)
        self.enter_username.place(relx=0.375, rely=0.37, height=34
                , relwidth=0.195)
        self.enter_username.configure(background="white")
        self.enter_username.configure(disabledforeground="#a3a3a3")
        self.enter_username.configure(font="-family {Courier New} -size 10")
        self.enter_username.configure(foreground="#000000")
        self.enter_username.configure(highlightbackground="#d9d9d9")
        self.enter_username.configure(highlightcolor="black")
        self.enter_username.configure(insertbackground="black")
        self.enter_username.configure(selectbackground="#c4c4c4")
        self.enter_username.configure(selectforeground="black")
        username=self.enter_username.get()

        self.sign_up = tk.Button(top)
        self.sign_up.place(relx=0.443, rely=0.45, height=43, width=116)
        self.sign_up.configure(activebackground="#ececec")
        self.sign_up.configure(activeforeground="#000000")
        self.sign_up.configure(background="#7b003e")
        self.sign_up.configure(disabledforeground="#a3a3a3")
        self.sign_up.configure(foreground="#fc94b8")
        self.sign_up.configure(highlightbackground="#d9d9d9")
        self.sign_up.configure(highlightcolor="black")
        self.sign_up.configure(pady="0")
        self.sign_up.configure(text='''Sign Up''')
        self.sign_up.configure(command=sign_up)

        self.Return = tk.Button(top)
        self.Return.place(relx=0.443, rely=0.519, height=43, width=116)
        self.Return.configure(activebackground="#ececec")
        self.Return.configure(activeforeground="#000000")
        self.Return.configure(background="#7b003e")
        self.Return.configure(disabledforeground="#a3a3a3")
        self.Return.configure(foreground="#fc94b8")
        self.Return.configure(highlightbackground="#d9d9d9")
        self.Return.configure(highlightcolor="black")
        self.Return.configure(pady="0")
        self.Return.configure(text='''Return''')
        self.Return.configure(command=return_back)

if __name__ == '__main__':
    vp_start_gui()