#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 06, 2019 08:32:01 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import sign_in_support
global username

def sign_in():
    import your_songs as ys
    import sign_up as su
    root.destroy()
    ys.vp_start_gui()

def return_back():
    import front_page as fp
    root.destroy()
    fp.vp_start_gui()

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global  w, root
    root = tk.Tk()
    root.state('zoomed')
    top = Toplevel1 (root)
    sign_in_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    sign_in_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font11 = "-family {Yu Gothic Light} -size 22 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("1250x650")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Sign In")
        top.configure(background="#ffffff")

        self.ask_username = tk.Message(top)
        self.ask_username.place(relx=0.389, rely=0.28, relheight=0.05
                , relwidth=0.21)
        self.ask_username.configure(background="#ffffff")
        self.ask_username.configure(font=font11)
        self.ask_username.configure(foreground="#7b003e")
        self.ask_username.configure(highlightbackground="#d9d9d9")
        self.ask_username.configure(highlightcolor="black")
        self.ask_username.configure(text='''Enter your username''')
        self.ask_username.configure(width=356)

        self.enter_username = tk.Entry(top)
        self.enter_username.place(relx=0.375, rely=0.37, height=34
                , relwidth=0.23)
        self.enter_username.configure(background="white")
        self.enter_username.configure(disabledforeground="#a3a3a3")
        self.enter_username.configure(font="-family {Courier New} -size 10")
        self.enter_username.configure(foreground="#000000")
        self.enter_username.configure(insertbackground="black")
        username=self.enter_username.get()
        
        self.sign_in = tk.Button(top)
        self.sign_in.place(relx=0.443, rely=0.45, height=43, width=116)
        self.sign_in.configure(activebackground="#ececec")
        self.sign_in.configure(activeforeground="#000000")
        self.sign_in.configure(background="#7b003e")
        self.sign_in.configure(disabledforeground="#a3a3a3")
        self.sign_in.configure(foreground="#fc94b8")
        self.sign_in.configure(highlightbackground="#d9d9d9")
        self.sign_in.configure(highlightcolor="black")
        self.sign_in.configure(pady="0")
        self.sign_in.configure(text='''Sign In''')
        self.sign_in.configure(command=sign_in)

        self.Return = tk.Button(top)
        self.Return.place(relx=0.443, rely=0.519, height=43, width=116)
        self.Return.configure(activebackground="#ececec")
        self.Return.configure(activeforeground="#000000")
        self.Return.configure(background="#7b003e")
        self.Return.configure(disabledforeground="#a3a3a3")
        self.Return.configure(foreground="#fc94b8")
        self.Return.configure(highlightbackground="#d9d9d9")
        self.Return.configure(highlightcolor="black")
        self.Return.configure(pady="0")
        self.Return.configure(text='''Return''')
        self.Return.configure(command=return_back)

if __name__ == '__main__':
    vp_start_gui()